<?= $this->render('common/top-bar-list.phtml'); ?>
<div class="container">
<div class="row">
<?= $this->render('common/message.phtml'); ?>
</div>
</div>
<div class="container panel panel-default">	
<form name="usuarios-list" id="usuarios" action="" method="post">
		<table class="table table-condensed table-hover table-striped">
			<thead>
				<tr>
					<th>
						<input type="checkbox" id="checkAll" title="Seleciona todos os itens">
					</th>
					<th>Nome</th>						
					<th>Situação</th>
					<th>Conjugue</th>
					<th>Telefone</th>
					<th class="text-center" >Histórico</th>
					<th class="text-center" >Visitar?</th>				
				</tr>
			</thead>
			<tbody>	
				<?php foreach ($this->paginator as $key => $data) : ?>					
					<?php
					   $data = array_merge($data, json_decode($data['params'], true));
					?>				
					<tr  <?php echo $data['visitas'] == 'Não' ? 'class="danger"' : ''  ?> >
					<td><input class="checkbox" id="<?= $data['id']; ?>" type="checkbox"
						name="<?= $data['id']; ?>"></td>
					<td>
						<a href="<?= $this->baseUrl() ?>/usuarios/edit/id/<?= $data['id'] ?>">
							<?= $data['nome']; ?>
						</a>
					</td>
					<td>
						<?= $data['situacao']; ?>
					</td>
					<td>
						<?= $data['nome_conjugue']; ?>
					</td>		
					<td>
						<?= $data['telefone']; ?>
					</td>	
					<td class="text-center" >
						<a class="btn btn-info btn-md" href="<?= $this->baseUrl() ?>/usuarios/resumo/id/<?= $data['id'] ?>" >
							<i class="glyphicon glyphicon-list-alt" ></i>
						</a>
					</td>	
					<td class="text-center" >						
						<?php if($data['visitas'] == 'Sim') : ?>
							<span class="btn" ><i class="glyphicon glyphicon-ok" ></i></span>
						<?php else : ?>
							<span class="btn" ><i class="glyphicon glyphicon-ban-circle" ></i></span>
						<?php endif;?>
					</td>
				</tr>
				<?php endforeach; ?>
		</tbody>
		</table>
		<input type="hidden" name="search" value="<?= isset($this->data['search']) ? $this->data['search'] : '' ?>" >		
	</form>
	
	<?php if($this->paginator) : ?>
    	<?= $this->paginationControl($this->paginator, 'Sliding', 'common/pagination.phtml'); ?>	
    <?php endif; ?>    
    
    <?php if($this->paginator->getCurrentItemCount() == 0) : ?>
    	<div class="alert alert-warning text-center" >Nenhum dado encontrado!</div>
    <?php endif;?>
	
</div>


<?php //Pegando o script.js ?>
<?= $this->render('common/scripts-js/script-bar-list.phtml'); ?>
